server:
  port: 8082
spring:
  application:
    name: location-verifier-service
  datasource:
    url: jdbc:mysql://location-verification.crv9qy09q0zr.us-east-1.rds.amazonaws.com:3306/verifierDB?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    username: admin
    password: 1522onur
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect

    
ntp-service.url: tr.pool.ntp.org